# Generated by Django 2.2 on 2020-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_event_autoreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='password',
            field=models.CharField(blank=True, max_length=32, verbose_name='Passwort'),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='participant',
            name='subcode',
            field=models.CharField(blank=True, max_length=16, verbose_name='Anmeldecode'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
