# Generated by Django 2.2 on 2020-04-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200412_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='namecode',
            field=models.CharField(default='BekkiTristan', max_length=32, verbose_name='Shortcut'),
            preserve_default=False,
        ),
    ]
