# Generated by Django 2.2 on 2020-04-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_event_namecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
