# Generated by Django 2.2 on 2020-04-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200412_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participation',
            field=models.IntegerField(choices=[(0, '---'), (1, 'ich komme'), (2, 'weiß noch nicht')], default=0, verbose_name='Teilnahme'),
        ),
    ]
