# Generated by Django 2.2 on 2020-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_participant_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participation',
            field=models.IntegerField(choices=[(0, '---'), (1, 'ich komme'), (2, 'ich komme nicht'), (3, 'weiß noch nicht')], default=0, verbose_name='Teilnahme'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='subcode',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='Anmeldecode'),
        ),
    ]
