# Generated by Django 2.2 on 2020-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200413_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='subcode',
            field=models.CharField(blank=True, max_length=16, verbose_name='Anmeldecode'),
        ),
    ]
