# Generated by Django 2.2 on 2020-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='notes',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
