# Generated by Django 2.2 on 2020-04-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_contribution_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Contribution')),
            ],
        ),
    ]
