# Generated by Django 2.2 on 2020-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='ci',
            name='subcode',
            field=models.CharField(blank=True, max_length=16, verbose_name='Anmeldecode'),
        ),
    ]
