# Generated by Django 2.2 on 2020-04-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_ci_subcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ci',
            new_name='Ciiiii',
        ),
    ]
