# Generated by Django 2.2 on 2020-04-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200414_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciiiii',
            new_name='Ci',
        ),
    ]
