# Generated by Django 2.2 on 2020-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200414_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ci',
            name='guestname',
            field=models.CharField(default='-', max_length=100, verbose_name='Name'),
        ),
    ]
