# Generated by Django 2.2 on 2020-04-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_ci_guestname'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participatecss',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='ci',
            name='guestname',
            field=models.CharField(default='-', max_length=100, verbose_name='Gastname'),
        ),
    ]
