# Generated by Django 2.2 on 2020-04-20 12:54

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_checkoutlist_coli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coli',
            name='guestname',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Gastname'),
        ),
        migrations.AlterField(
            model_name='coli',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.get_upload_filename_image, verbose_name='Bild'),
        ),
    ]
