# Generated by Django 2.2 on 2020-04-20 21:06

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_coli_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coli',
            name='subcode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Anmeldecode'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.get_upload_filename_document, verbose_name='Dokument'),
        ),
    ]
