# Generated by Django 2.2 on 2020-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20200420_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
